version: "3"

services:
  nats1:
    image: nats:latest
    container_name: nats1
    command: >
      -js
      --server_name nats1
      --cluster_name capventis-cluster
      --cluster nats://0.0.0.0:6222
      --routes nats://nats2:6222,nats://nats3:6222
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6222:6222" # Cluster port

  nats2:
    image: nats:latest
    container_name: nats2
    command: >
      -js
      --server_name nats2
      --cluster_name capventis-cluster
      --cluster nats://0.0.0.0:6222
      --routes nats://nats1:6222,nats://nats3:6222
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6223:6222" # Cluster port

  nats3:
    image: nats:latest
    container_name: nats3
    command: >
      -js
      --server_name nats3
      --cluster_name capventis-cluster
      --cluster nats://0.0.0.0:6222
      --routes nats://nats1:6222,nats://nats2:6222
    ports:
      - "6224:6222" # Cluster port only

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
